name: book_page_tracker
description: "A page tracker app, for use while reading multiple books at once."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.01+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
